In [5]:
#  Importing the 5 libaray of the python 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sqlite3

In [6]:
# Importing the data via sqllite 
conn = sqlite3.connect("customer_churn.db")

sql_query = """
        SELECT name 
        FROM sqlite_master
        WHERE type = 'table'
"""

tables = pd.read_sql(sql_query,conn) 

# Creating DATAFRAME for each tables 
for table_name in tables['name'] : 
    df = pd.read_sql(f"SELECT * FROM {table_name}",conn)
    globals()[f"df_{table_name}"] = df 
    print(f"Created dataframe: df_{table_name}")

conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [7]:
#  printing the data of the table 1 
df_db_customer

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10 00:00:00,NaN,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,NaN,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07 00:00:00,NaN,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,NaN,None
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00,NaN,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01 00:00:00,NaN,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,NaN,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,NaN,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,NaN,None

In [8]:
#  there are following stpes we have to perform for the data analysis 
#  1 --> import the sql data into the pandas 
#  2 --> perform the data cleaning

In [9]:
# here we check the info of the table 1  
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 2.5+ KB

In [10]:
#  the following mistakes in the tbale 1 we have to correct it 
#  1 --> repalce column  --> name 
#  2 --> drop column --> interest and pincode 
#  3 --> find the  missing values column--> country 
#  4 --> update data types of column --> dob 
#  5 --> update values of column -->gender

In [11]:
#  1 --> repalce column  --> name 
df_db_customer.rename(columns = {'name' : 'customer_name'},inplace = True)
df_db_customer

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10 00:00:00,NaN,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,NaN,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07 00:00:00,NaN,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,NaN,None
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00,NaN,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01 00:00:00,NaN,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,NaN,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,NaN,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,NaN,None

In [12]:
#  2 --> drop column --> interest and pincode 
df_db_customer.drop(df_db_customer.columns[-2:],axis = 1)
df_db_customer

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10 00:00:00,NaN,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,NaN,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07 00:00:00,NaN,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,NaN,None
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00,NaN,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01 00:00:00,NaN,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,NaN,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,NaN,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,NaN,None

In [13]:
#  4 --> update data types of column --> dob  
df_db_customer['dob'] = pd.to_datetime(df_db_customer['dob'])
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   customer_name  21 non-null     str
 2   country        18 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     datetime64[us]
 6   interests      4 non-null      str
 7   pincode        0 non-null      object
dtypes: datetime64[us](1), object(1), str(6)
memory usage: 2.2+ KB

In [14]:
#  5 --> update values of column -->gender  
# df_db_customer['gender'].unique()

df_db_customer['gender'] = df_db_customer['gender'].replace(
                           {
                               'Men' : 'Male',
                               'Women' : 'Female'
                           }
)
df_db_customer

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05,drama,None
5,0013-MHZWF,durga,NaN,Delhi,Female,1988-12-10,NaN,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21,NaN,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Female,1985-07-07,NaN,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29,NaN,None
10,0017-DINOC,shiva,India,Maharashtra,Male,1997-01-22,NaN,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01,NaN,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25,NaN,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Male,1979-11-11,NaN,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Male,1991-05-14,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Female,1977-10-06,NaN,None

In [15]:
#  3 --> find the  missing values column--> country 

# Find the missing values in the coutry columns 
df_db_customer['country'].isna()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
Name: country, dtype: bool

In [16]:
state_country_mapping = df_db_customer.dropna(subset = ['country']).set_index('state')['country'].to_dict()
df_db_customer['country'] = df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))
df_db_customer[df_db_customer['country'].isna()]

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob, interests, pincode]
Index: []

In [17]:
df_db_customer[['country','state']]

   country          state
0    India    Maharashtra
1    India      Karnataka
2    India          Delhi
3    India       Nagaland
4    India          Delhi
5    India          Delhi
6    India      Meghalaya
7    India      Rajasthan
8    Nepal      Kathmandu
9    Nepal      Kathmandu
10   India    Maharashtra
11   India      Karnataka
12   India      Telangana
13   India      Meghalaya
14   India  Uttar Pradesh
15   India          Delhi
16   India      Meghalaya
17   India      Rajasthan
18   India      Telangana
19   India  Uttar Pradesh
20   India    Maharashtra

In [18]:
# Now printing the updated table 
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   customer_name  21 non-null     str
 2   country        21 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     datetime64[us]
 6   interests      4 non-null      str
 7   pincode        0 non-null      object
dtypes: datetime64[us](1), object(1), str(6)
memory usage: 2.2+ KB

In [19]:
#  printing the data of table 2 
df_db_subscription

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88
5,0013-MHZWF,2022-06-18,Paid,2025-06-18,Standard,Annual,NaN,NaN,17.99,720,22
6,0013-SMEOE,2021-09-30,Refferal,2024-09-30,Basic,Monthly,2024-11-15,Not enough content,8.99,230,79
7,0014-BMAQU,2020-02-14,Organic,2025-02-14,Premium,Annual,NaN,NaN,22.99,1840,5
8,0015-UOCOJ,2023-07-22,Organic,2024-07-22,Standard,Monthly,NaN,NaN,13.99,240,34
9,0016-QLJIS,2022-04-03,Organic,2025-04-03,Basic,Annual,NaN,NaN,6.99,335,41
10,0017-DINOC,2021-12-01,Organic,2025-12-01,Premium,Annual,NaN,NaN,22.99,1610,14
11,0017-IUDMW,2023-03-17,Refferal,2024-03-17,Standard,Monthly,2024-05-01,Poor streaming quality,7.99,270,83
12,0018-NYROU,2020-10-09,Organic,2025-10-09,Standard,Annual,NaN,NaN,13.99,980,19
13,0019-EFAEP,2022-08-25,Refferal,2024-08-25,Basic,Monthly,2024-10-31,Switched to competitor,12.99,160,76
14,0019-GFNTW,2019-11-11,Paid,2025-11-11,Premium,Annual,NaN,NaN,92.99,2185,3
15,0020-INWCK,2023-05-06,Organic,2025-05-06,Standard,Monthly,NaN,NaN,13.99,640,58
16,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,NaN,NaN,20.99,550,62
17,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,NaN,NaN,13.99,840,27
18,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99
19,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,NaN,NaN,22.99,1955,7
20,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,NaN,NaN,13.99,790,47

In [20]:
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     str
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     str
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      str
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), str(8)
memory usage: 3.1 KB

In [21]:
#  The various problem in subsciption table 
# 1 --> change the data type str to date time

In [22]:
# 1 --> change the data type str to date time 
list_date = ['subscription_start_date','renewal_date','cancellation_date']
df_db_subscription[list_date] = df_db_subscription[list_date].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     datetime64[us]
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     datetime64[us]
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      datetime64[us]
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[us](3), float64(1), int64(2), str(5)
memory usage: 2.7 KB

In [23]:
df_db_subscription

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88
5,0013-MHZWF,2022-06-18,Paid,2025-06-18,Standard,Annual,NaT,NaN,17.99,720,22
6,0013-SMEOE,2021-09-30,Refferal,2024-09-30,Basic,Monthly,2024-11-15,Not enough content,8.99,230,79
7,0014-BMAQU,2020-02-14,Organic,2025-02-14,Premium,Annual,NaT,NaN,22.99,1840,5
8,0015-UOCOJ,2023-07-22,Organic,2024-07-22,Standard,Monthly,NaT,NaN,13.99,240,34
9,0016-QLJIS,2022-04-03,Organic,2025-04-03,Basic,Annual,NaT,NaN,6.99,335,41
10,0017-DINOC,2021-12-01,Organic,2025-12-01,Premium,Annual,NaT,NaN,22.99,1610,14
11,0017-IUDMW,2023-03-17,Refferal,2024-03-17,Standard,Monthly,2024-05-01,Poor streaming quality,7.99,270,83
12,0018-NYROU,2020-10-09,Organic,2025-10-09,Standard,Annual,NaT,NaN,13.99,980,19
13,0019-EFAEP,2022-08-25,Refferal,2024-08-25,Basic,Monthly,2024-10-31,Switched to competitor,12.99,160,76
14,0019-GFNTW,2019-11-11,Paid,2025-11-11,Premium,Annual,NaT,NaN,92.99,2185,3
15,0020-INWCK,2023-05-06,Organic,2025-05-06,Standard,Monthly,NaT,NaN,13.99,640,58
16,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,NaT,NaN,20.99,550,62
17,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,NaT,NaN,13.99,840,27
18,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99
19,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,NaT,NaN,22.99,1955,7
20,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,NaT,NaN,13.99,790,47

In [24]:
# printing the thrid table
df_db_support

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN
5,0017-IUDMW,2024-04-10 00:00:00,Y,25,None,NaN
6,0019-EFAEP,2024-09-27 00:00:00,Y,30,None,NaN
7,0022-TCJCI,2024-09-13 00:00:00,Y,10,None,NaN
8,0022-TCJCI,2024-09-14 00:00:00,N,90,None,received refund

In [25]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN

In [26]:
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      str
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      str
dtypes: int64(1), object(1), str(4)
memory usage: 895.0+ bytes

In [27]:
#  after analysis the 3rd table 
#  1 --> remove column --> col_1 and comment
#  2 --> change data type -->  complaint_date

In [28]:
 #  1 --> remove column --> col_1 and comment 
df_db_support.drop(df_db_support. columns[-2:],axis = 1)
df_db_support

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN
5,0017-IUDMW,2024-04-10 00:00:00,Y,25,None,NaN
6,0019-EFAEP,2024-09-27 00:00:00,Y,30,None,NaN
7,0022-TCJCI,2024-09-13 00:00:00,Y,10,None,NaN
8,0022-TCJCI,2024-09-14 00:00:00,N,90,None,received refund

In [29]:
#  2 --> change data type -->  complaint_date 
df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])
df_db_support

   customerid complaint_date escalations  csat_score col_1            comment
0  0003-MKNFE     2024-08-28           N          60  None      service issue
1  0003-MKNFE     2024-08-28           Y          10  None     demaned refund
2  0013-EXCHZ     2024-01-20           Y          20  None                NaN
3  0013-MHZWF     2025-03-18           N          90  None  guidance to renew
4  0013-SMEOE     2024-11-01           N          30  None                NaN
5  0017-IUDMW     2024-04-10           Y          25  None                NaN
6  0019-EFAEP     2024-09-27           Y          30  None                NaN
7  0022-TCJCI     2024-09-13           Y          10  None                NaN
8  0022-TCJCI     2024-09-14           N          90  None    received refund

In [30]:
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      datetime64[us]
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      str
dtypes: datetime64[us](1), int64(1), object(1), str(3)
memory usage: 724.0+ bytes

In [31]:

# HEADING NUMBER 3 
###################################################################  FEATURE ENGINEERING ##############################################################
# here where the cancelletion date is present means user is churn from our platfrom

# Creating of new column using existing columns 
df_db_subscription['churn_flag'] = np.where(df_db_subscription['cancellation_date'].notna(),1,0)

In [32]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,NaN,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,NaN,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [33]:
  #  first fix the support table duplicate customer id then we merge 
df = (
    df_db_subscription
        .merge(df_db_customer,on = 'customerid',how = 'left')
        .merge(df_db_support,on = 'customerid',how = 'left')
)

In [34]:
df.shape

(23, 24)

In [35]:
df_db_customer.shape

(21, 8)

In [36]:
df_db_subscription.shape

(21, 12)

In [37]:
df_db_support.shape

(9, 6)

In [38]:
# here there is extra column in the df_db_support table 
df_db_support

   customerid complaint_date escalations  csat_score col_1            comment
0  0003-MKNFE     2024-08-28           N          60  None      service issue
1  0003-MKNFE     2024-08-28           Y          10  None     demaned refund
2  0013-EXCHZ     2024-01-20           Y          20  None                NaN
3  0013-MHZWF     2025-03-18           N          90  None  guidance to renew
4  0013-SMEOE     2024-11-01           N          30  None                NaN
5  0017-IUDMW     2024-04-10           Y          25  None                NaN
6  0019-EFAEP     2024-09-27           Y          30  None                NaN
7  0022-TCJCI     2024-09-13           Y          10  None                NaN
8  0022-TCJCI     2024-09-14           N          90  None    received refund

In [39]:
df_db_support['complaint_count'] = df_db_support.groupby('customerid')['customerid'].transform('count')

In [40]:
df_db_support = df_db_support.sort_values('complaint_date').drop_duplicates('customerid', keep = 'last')

In [41]:
df_db_support

,customerid,complaint_date,escalations,csat_score,col_1,comment,complaint_count
2,0013-EXCHZ,2024-01-20,Y,20,None,NaN,1
5,0017-IUDMW,2024-04-10,Y,25,None,NaN,1
1,0003-MKNFE,2024-08-28,Y,10,None,demaned refund,2
8,0022-TCJCI,2024-09-14,N,90,None,received refund,2
6,0019-EFAEP,2024-09-27,Y,30,None,NaN,1
4,0013-SMEOE,2024-11-01,N,30,None,NaN,1
3,0013-MHZWF,2025-03-18,N,90,None,guidance to renew,1

In [42]:
# merge 3 tabels 
df = (
    df_db_subscription
        .merge(df_db_customer,on = 'customerid',how = 'left')
        .merge(df_db_support,on = 'customerid',how = 'left')
)
df.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,...,gender,dob,interests,pincode,complaint_date,escalations,csat_score,col_1,comment,complaint_count
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,...,Male,1982-04-12,travel,None,NaT,NaN,NaN,NaN,NaN,NaN
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,...,Male,1995-11-23,NaN,None,2024-08-28,Y,10.0,None,demaned refund,2.0
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,NaN,6.99,210,...,Female,1978-02-15,movie,None,NaT,NaN,NaN,NaN,NaN,NaN
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,NaN,22.99,1725,...,Male,2001-08-30,NaN,None,NaT,NaN,NaN,NaN,NaN,NaN
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,...,Female,1990-05-05,drama,None,2024-01-20,Y,20.0,None,NaN,1.0

In [43]:
df.shape

(21, 25)

PERFORMING DATA ANALYSIS

In [46]:
#  to export the csv 
# here index false because we do  not want the index like 0,1,2,etc 
df.to_csv('exported_churn_data.csv',index = False)

HERE WE HAVE FIND THE CHURN RATE

In [51]:
churn_rate = df['churn_flag'].mean()*100
print("Churn Rate = ", round(churn_rate,2),"%")

Churn Rate =  28.57 %

RETENTION RATE

In [52]:
retention_rate = 100 - churn_rate
print("Retention Rate = ", round(retention_rate,2), "%")

Retention Rate =  71.43 %

WHICH TYPE OF USER IS CHURN FROM PLAN TYPE

In [53]:
df.head(2)

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,...,gender,dob,interests,pincode,complaint_date,escalations,csat_score,col_1,comment,complaint_count
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,...,Male,1982-04-12,travel,None,NaT,NaN,NaN,NaN,NaN,NaN
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,...,Male,1995-11-23,NaN,None,2024-08-28,Y,10.0,None,demaned refund,2.0

In [59]:
churn_by_plan_type = (df.groupby('plan_type')['churn_flag'].mean().mul(100).round(2).reset_index(name = 'churn_by_pct'))
print(churn_by_plan_type)

  plan_type  churn_by_pct
0     Basic         60.00
1   Premium         14.29
2  Standard         22.22

Here more users are churn from the BASIC plan type 
Less Users are Churn from the PREMIUM plan type

In [65]:
# Here we have to find the churn by state + sum(revenue) & count of users 
churn_by_state_revenue_user_count = df.groupby('state').agg({
    'monthly_charges' : 'sum',
    'customerid' : 'count'
})
churn_by_state_revenue_user_count

               monthly_charges  customerid
state
Delhi                    52.96           4
Karnataka                20.98           2
Kathmandu                20.98           2
Maharashtra              50.97           3
Meghalaya                42.97           3
Nagaland                 22.99           1
Rajasthan                36.98           2
Telangana                30.98           2
Uttar Pradesh           115.98           2

In [67]:
#  here we have find the subscriptin_type + sum(revenue) & count of users 
churn_by_subs_type_revenue_user_count = df.groupby('subscription_type').agg({
    'monthly_charges' : 'sum',
    'customerid' : 'count'
})
churn_by_subs_type_revenue_user_count

                   monthly_charges  customerid
subscription_type
Organic                     145.91           9
Paid                        174.94           6
Refferal                     74.94           6

Here we have to calculate the AVERAHE REVENUE PER USER

In [68]:
df.columns   # isase pura column visual ho jayega

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'interests', 'pincode', 'complaint_date', 'escalations', 'csat_score',
       'col_1', 'comment', 'complaint_count'],
      dtype='str')

In [71]:
ARPU = df['monthly_charges'].mean()    # ARPU(AVAERAGE REVENUE PER USER )
print("ARPU = ", round(ARPU,2))

ARPU =  18.85

In [78]:
#  lets we have to find the age of the customer 
today = pd.Timestamp.today()
df['Age'] = ((today- df['dob']).dt.days // 365)
df.head(2)

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,...,dob,interests,pincode,complaint_date,escalations,csat_score,col_1,comment,complaint_count,Age
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,...,1982-04-12,travel,None,NaT,NaN,NaN,NaN,NaN,NaN,44
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,...,1995-11-23,NaN,None,2024-08-28,Y,10.0,None,demaned refund,2.0,30

In [86]:
# Average custormer tenure 
#  meand our customer is using our ott or not : cancellation date 
today 
df['tenure_days '] = np.where(
    df['cancellation_date'].notna(),
    (df['cancellation_date'] - df['subscription_start_date']).dt.days,
    (today - df['subscription_start_date']).dt.days
)
avg_tenure = df['tenure_days '].mean()
print("Avg Tenure (days) = ", round(avg_tenure,2))

Avg Tenure (days) =  1545.14

Find the revenue risk --> after the user quit how much revenue loss

In [89]:
revenue_at_risk = df.loc[df['churn_flag'] == 1,'monthly_charges'].sum()
print("Revenue_At_Risk (Rs. K) = ", round(revenue_at_risk,2))

Revenue_At_Risk (Rs. K) =  73.94

Escalations rate

In [96]:
escalations_rate = (df['escalations'] == 'Y').mean()*100
print("escalations_rate = ", round(escalations_rate,2), "%")

escalations_rate =  19.05 %

Average Complaint Per user

In [97]:
df.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'interests', 'pincode', 'complaint_date', 'escalations', 'csat_score',
       'col_1', 'comment', 'complaint_count', 'Age', 'tenure_days '],
      dtype='str')

In [100]:
complaint_rate = df['complaint_count'].sum()/ df['customerid'].nunique()
print("Complaint_Rate = ",round(complaint_rate,2))

Complaint_Rate =  0.43

In [115]:
df.head(2)

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,...,interests,pincode,complaint_date,escalations,csat_score,col_1,comment,complaint_count,Age,tenure_days
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,NaN,13.99,627,...,travel,None,NaT,0,NaN,NaN,NaN,NaN,44,2018.0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,...,NaN,None,2024-08-28,0,10.0,None,demaned refund,2.0,30,1501.0

Correlation Esclation vs churn

In [116]:
df['escalations'] = np.where(df['escalations'] == 'Y', 1, 0)

corr_df = df[['escalations','churn_flag']].dropna()

# Only compute correlation if both columns have variation
if corr_df['escalations'].nunique() > 1 and corr_df['churn_flag'].nunique() > 1:
    correlation = corr_df['escalations'].corr(corr_df['churn_flag'])
    print("Correlation Between escalations and churn =", round(correlation, 2))
else:
    print("Correlation cannot be computed because one column has no variation.")

Correlation cannot be computed because one column has no variation.

In [117]:
# create a column using churn risk 
df['churn_score'].head()

0    12
1    91
2    34
3     8
4    88
Name: churn_score, dtype: int64

In [119]:
#  create new column using existing columns 
conditions = [
    (df['churn_score'] < 50),
    (df['churn_score'] >=50) & (df['churn_score'] <70),
    (df['churn_score'] >=70)
 
]

choices = ['low', 'medium', 'high']

df['churn_risk'] = np.select(conditions,choices,default = 'unkown')

In [121]:
df[['churn_score', 'churn_risk']]

    churn_score churn_risk
0            12        low
1            91       high
2            34        low
3             8        low
4            88       high
5            22        low
6            79       high
7             5        low
8            34        low
9            41        low
10           14        low
11           83       high
12           19        low
13           76       high
14            3        low
15           58     medium
16           62     medium
17           27        low
18           99       high
19            7        low
20           47        low